USE master
go


CREATE DATABASE BDCibertec
GO

USE BDCibertec
GO

CREATE TABLE SEDE(
	ID INT IDENTITY PRIMARY KEY,
	NOMBRE VARCHAR(50),
	ANIO_APERTURA CHAR(4),
	NUM_MATRICULADOS INT,
	NUM_PROFESORES INT
)
GO

INSERT INTO SEDE(NOMBRE, ANIO_APERTURA, NUM_MATRICULADOS, NUM_PROFESORES) VALUES
('Cercado de Lima', '2019', 2000, 50),
('Breña', '2015', 2500, 55),
('San Juan de Lurigancho', '2016', 3000, 60),
('Independencia', '2016', 1800, 35)
GO

select * from SEDE